### PR TITLE
Switch to Observable.fromAsync

### PR DESCRIPTION
**Pull request by Plastix**
`Observable.create()` is hard to get right because you have to take special
care to obey the Observable lifecycle and support backpressure. This
commit switches `Observable.create()` in favor of `Observable.fromAsync()` which
supports backpressure and obeys the observable lifecycle natively.

### CODE REVIEW

**Comment by kmdupr33** [comment]
Nice. Thanks for this.

**Comment by antonky** [comment]
`Observable.fromAsync()` [is deprecated](http://reactivex.io/RxJava/javadoc/rx/Observable.html#fromAsync%28rx.functions.Action1,%20rx.AsyncEmitter.BackpressureMode%29)

**Comment by Plastix** [comment]
@nakamin This library uses RxJava `1.1.8` so `fromAsync()` isn't deprecated. It is only deprecated in newer versions. Feel free to open a PR to upgrade RxJava and change it!

**Comment by antonky** [comment]
Oops sorry 😆

**Pull request merged**
